# 服务端口
server:
  port: 8150
  # 服务名
spring:
  application:
    name: yygh-service-user
  profiles:
    active: dev
# mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.178.196:3306/atguigu_yygh_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: cyinfo666888666
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        namespace: ffdb8c0e-e8b3-464d-b59b-19bfd893eb65
        server-addr: 139.196.178.196:8848
mybatis-plus:
  mapper-locations: classpath:com/atguigu/study/yygh/user/mapper/*.xml